spring:
  application:
    name:canary-sever
  datasource:
    url: jdbc:mysql://localhost:3306/canary?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: MysqlRoot@2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host:localhost
    port:6379


mybatis:
  type-aliases-package: com.github.shen.canary.**.entity
  configuration:
    map-underscore-to-camel-case: false
  logic-delete: # 显式关闭逻辑删除
    enabled: false

logging:
  level:
    org.zalando.logbook: TRACE #输出request-log
    com.github.shen.canary.server: TRACE